### PR TITLE
Add support for Python SDK and non-setuptools Python components.

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[build-openmpf-components/build_components.py, line 598 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20#-LCEhi8s4XzoPMSKMpCC:-LCEhi8s4XzoPMSKMpCD:b-ihb4dc) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/0894a70fb78cb0f10024768ecf6711d4c996addf/build-openmpf-components/build_components.py#L598)):*
> ```Python
>         if not PipUtil.has_setup_py_file(self.src_dir):
>             raise Exception(
>                 'Unable to build Python SDK because %s does not contain a setup.py file.'
> ```

Is this just a sanity check. Since we control the code, this exception should never occur, right?

---

*[build-openmpf-components/build_components.py, line 688 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20#-LCEiBh_0LyynmXE6qN8:-LCEiBh_0LyynmXE6qN9:brwxjgk) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/0894a70fb78cb0f10024768ecf6711d4c996addf/build-openmpf-components/build_components.py#L688)):*
> ```Python
>             # TODO: Call pip wheel
>             # subprocess.check_call(('pip', 'wheel', '--wheel-dir', 'path/to/wheelhouse', self.src_dir))
>             raise NotImplementedError('setup.py for components not yet implemented')
> ```

Are you actively working on the setup.py issue, or should we set it aside for now and work on the video capture and image reader tools?

I'm just thinking that if we're postponing that work, we should capture it in a separate task.

Let me know how you want to handle it.

---

*[build-openmpf-components/test/test-component-cmdline-args.txt, line 6 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20#-LCEoAZD1xp0g5C1Mv1c:-LCEoAZE8b142hQ4DfsU:bkhmtck) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/0894a70fb78cb0f10024768ecf6711d4c996addf/build-openmpf-components/test/test-component-cmdline-args.txt#L6)):*
> ```
> ../../openmpf-java-component-sdk
> -psdk
> ../../openmpf-python-component-sdk/api
> ```

The C++ SDK has a top-level CMakeLists.txt file, and the Java SDK has a top-level pom. Those are used to build the detection/*api* sub-directories. I don't see anything like that in the Python SDK, so I understand the need for appending "api" here, but it's a bit inconsistent.

Instead, could we just have this script append "/api" to whatever the user provides? That should really be "/detection/api". See other comment.

Or is there a more pythonic way to include subdirectories in the build?

---

*[build-openmpf-components/test/test-mpf-package.json, line 54 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20#-LCEj9wE5P2A4uapazXi:-LCEj9wFBRpykGc0VUTe:b-ytjcs3) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/0894a70fb78cb0f10024768ecf6711d4c996addf/build-openmpf-components/test/test-mpf-package.json#L54)):*
> ```JSON
>             "name": "CaffeDetection",
>             "path": "../../openmpf-components/cpp/CaffeDetection"
>         },
> ```

Let's add Darknet here for completeness.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20)*

**Comment by jrobble** [comment]
*[build-openmpf-components/test/test-component-cmdline-args.txt, line 6 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20#-LCEoAZD1xp0g5C1Mv1c:-LCEpMqZCM9C3olzkool:bru725y) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/0894a70fb78cb0f10024768ecf6711d4c996addf/build-openmpf-components/test/test-component-cmdline-args.txt#L6)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The C++ SDK has a top-level CMakeLists.txt file, and the Java SDK has a top-level pom. Those are used to build the detection/*api* sub-directories. I don't see anything like that in the Python SDK, so I understand the need for appending "api" here, but it's a bit inconsistent.

Instead, could we just have this script append "/api" to whatever the user provides? That should really be "/detection/api". See other comment.

Or is there a more pythonic way to include subdirectories in the build?
</blockquote></details>

This is the other comment: https://github.com/openmpf/openmpf-python-component-sdk/pull/1#issuecomment-388399110

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20)*

**Comment by brosenberg42** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[build-openmpf-components/build_components.py, line 598 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20#-LCEhi8s4XzoPMSKMpCC:-LCEtFrG-qCDVLScDeaW:bfxsgsl) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/0894a70fb78cb0f10024768ecf6711d4c996addf/build-openmpf-components/build_components.py#L598)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this just a sanity check. Since we control the code, this exception should never occur, right?
</blockquote></details>

This exception will occur if the wrong path to the SDK is provided.

---

*[build-openmpf-components/build_components.py, line 688 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20#-LCEiBh_0LyynmXE6qN8:-LCEtedy-4jTGb_tQu0d:b-g1l28k) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/0894a70fb78cb0f10024768ecf6711d4c996addf/build-openmpf-components/build_components.py#L688)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Are you actively working on the setup.py issue, or should we set it aside for now and work on the video capture and image reader tools?

I'm just thinking that if we're postponing that work, we should capture it in a separate task.

Let me know how you want to handle it.
</blockquote></details>

I am currently working on the setup.py issue.

---

*[build-openmpf-components/test/test-component-cmdline-args.txt, line 6 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20#-LCEoAZD1xp0g5C1Mv1c:-LCFM7Si92srzWxiadnc:b-v2gkoj) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/0894a70fb78cb0f10024768ecf6711d4c996addf/build-openmpf-components/test/test-component-cmdline-args.txt#L6)):*
> Or is there a more pythonic way to include subdirectories in the build?

Not that I know of.

---

*[build-openmpf-components/test/test-mpf-package.json, line 54 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20#-LCEj9wE5P2A4uapazXi:-LCFMDyB8wKRYO_ELN2D:b-896fix) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/0894a70fb78cb0f10024768ecf6711d4c996addf/build-openmpf-components/test/test-mpf-package.json#L54)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's add Darknet here for completeness.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20)*

**Comment by jrobble** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/20)*

**Review by jrobble — APPROVED** [review]

**Pull request merged**
