### PR TITLE
Use full path instead of build id

### PR DESCRIPTION
**Pull request by brosenberg42**
---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/2)

### CODE REVIEW

**Comment by jrobble** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build-openmpf-components/build_components.py, line 533 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/2#-Knj9ayabSM_D0gmhlv-:-Knj9ayabSM_D0gmhlv0:b-tbzrp5) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/1c3014954a9dca35db8dcdd7968e9f991d67a383/build-openmpf-components/build_components.py#L533)):*
> ```Python
> 
>     def build(self):
>         sdk_build_dir = os.path.join(self._base_build_dir, 'openmpf-cpp-component-sdk-build')
> ```

Should we be using the full path here too for consistency? In the mpf-component-build dir I see:

home-mpf-git-openmpf-projects-openmpf-components-cpp-build
home-mpf-git-openmpf-projects-openmpf-contrib-components-cpp-build
home-mpf-git-openmpf-projects-openmpf-cpp-component-sdk-detection-examples-build
openmpf-cpp-component-sdk-build

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/2)*

**Comment by brosenberg42** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build-openmpf-components/build_components.py, line 533 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/2#-Knj9ayabSM_D0gmhlv-:-KnjMZXc7WLXIA4E6Unn:b-l52ass) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/1c3014954a9dca35db8dcdd7968e9f991d67a383/build-openmpf-components/build_components.py#L533)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we be using the full path here too for consistency? In the mpf-component-build dir I see:

home-mpf-git-openmpf-projects-openmpf-components-cpp-build
home-mpf-git-openmpf-projects-openmpf-contrib-components-cpp-build
home-mpf-git-openmpf-projects-openmpf-cpp-component-sdk-detection-examples-build
openmpf-cpp-component-sdk-build
</blockquote></details>

I think that having the full path makes it harder to figure out what is actually in that directory since the part of the name that is useful is all the way at the end. In the end I don't feel strongly one way or the other since people wouldn't normally be looking in this directory. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/2)*

**Comment by jrobble** [comment]
*[build-openmpf-components/build_components.py, line 533 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/2#-Knj9ayabSM_D0gmhlv-:-KnjQMfVBvABoKsw9N1j:b-ygu3jx) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/1c3014954a9dca35db8dcdd7968e9f991d67a383/build-openmpf-components/build_components.py#L533)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think that having the full path makes it harder to figure out what is actually in that directory since the part of the name that is useful is all the way at the end. In the end I don't feel strongly one way or the other since people wouldn't normally be looking in this directory. 
</blockquote></details>

One potential issue with the current approach is if for some reason they have two versions of the C++ SDK in two different directories then they would both use the same build dir.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/2)*

**Comment by jrobble** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/2#-:-Knjz9qJjDztEMFFMZvw:bnfp4nl)*

**Review by jrobble — APPROVED** [review]

**Pull request merged**
