### PR TITLE
Add docker only build option

### PR DESCRIPTION
**Pull request by hhuangMITRE**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/37)

### CODE REVIEW

**Comment by jrobble** [comment]
@hhuangmitre , in the future please make sure to select "develop" as the base branch. You selected "master" so there were a lot of unrelated changes shown in Reviewable. I made the switch and now everything looks right.

**Review by hhuangMITRE — COMMENTED** [review]
Thanks for catching that! Will do.
I based the branch off `develop` but forgot to make the base branch assignment  to `develop` when I made the PR request, my mistake. 

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/37#-:-M4onxO-10q03WRtQDv6:b-noyyk5)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jrobble)

**Comment by jrobble** [comment]
Works as expected. When the TrtisDetection path is specifically provided on the command line or package JSON file the build errors out. When a parent search path is provided the build succeeds. 

For my future reference, tested as follows:

# DOESN'T BUILD (TRTIS DETECTION IS NOT A PROJECT)
python3 build_components.py \
    -b ~/mpf-component-build \
    -p 2 \
    -j 4 \
    -csdk ~/git/openmpf-projects/openmpf-cpp-component-sdk \
    -jsdk ~/git/openmpf-projects/openmpf-java-component-sdk \
    -c ~/git/openmpf-projects/openmpf-components/cpp/TrtisDetection

# DOESN'T BUILD (BUILDS EVERYTHING ELSE)
python3 build_components.py \
    -b ~/mpf-component-build \
    -p 2 \
    -j 4 \
    -csdk ~/git/openmpf-projects/openmpf-cpp-component-sdk \
    -jsdk ~/git/openmpf-projects/openmpf-java-component-sdk \
    -c ~/git/openmpf-projects/openmpf-components/cpp

# DOESN'T BUILD (TRTIS DETECTION IS NOT A PROJECT)
mvn install -DskipTests -DskipITs -Dcargo.maven.skip=true -Dstartup.auto.registration.skip=false -Dmaven.tomcat.skip=true -Dcomponents.build.components=openmpf-components/cpp/TrtisDetection
	
# DOESN'T BUILD (BUILDS EVERYTHING ELSE)
mvn install -DskipTests -DskipITs -Dcargo.maven.skip=true -Dstartup.auto.registration.skip=false -Dmaven.tomcat.skip=true -Dcomponents.build.components=openmpf-components/cpp

# DOESN'T BUILD (TRTIS DETECTION IS NOT A PROJECT)
mvn install -DskipTests -DskipITs -Dcargo.maven.skip=true -Dcomponents.build.package.json=/home/mpf/Desktop/DOCKER/config-files/openmpf-minimal-face-and-trtis-package.json -Dstartup.auto.registration.skip=false -Dmaven.tomcat.skip=true

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/37)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jrobble — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/37#-:-MGiZ5Jk5jwJG5Wbp6Fc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
