### PR TITLE
Create a Dockerfile that builds ffmpeg with codecs

### PR DESCRIPTION
**Pull request by bquinn17**
To be used for transcoding media

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
Let's put the `ffmpeg` dir in a top-level dir called `docker`. 

Have you been able to build the image using the Dockerfile?

Please add a short `README.md` in the `ffmpeg` dir with this content:

```
# Overview

Run `docker build . -t openmpf_ffmpeg:latest` to create a Docker image with the ffmpeg binaries installed in `/apps/install/bin`.
```

Please review the above for correctness.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32#-:-Lm5bmfl16IZgtm6NzzP:bye91zg)* status: all files reviewed, 1 unresolved discussion (waiting on @bquinn17)

___
*[ffmpeg/Dockerfile, line 27 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32#-Lm5cqRrEul9kN_6LPAb:-Lm5cqRs4h_18zVNfw62:b-o2npnz) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/98fbf46ebeb80b21bec59b31e3a672097bd10dee/ffmpeg/Dockerfile#L27)):*
> ```Dockerfile
> 
> FROM centos:7.4.1708
> ```

Add a "Use at your own discretion, this file may be out of date!" disclaimer here.

**Review by bquinn17 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32#-:-LmBWvRi4riHG3DOvGLG:b-896fix)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[ffmpeg/Dockerfile, line 27 at r1](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32#-Lm5cqRrEul9kN_6LPAb:-LmAPx2oC4r9lLEKaDN9:b-896fix) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/98fbf46ebeb80b21bec59b31e3a672097bd10dee/ffmpeg/Dockerfile#L27)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add a "Use at your own discretion, this file may be out of date!" disclaimer here.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32)* status: all files reviewed, 1 unresolved discussion (waiting on @bquinn17)

___
*[docker/ffmpeg/Dockerfile, line 166 at r2](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32#-LmBZEl-EFJ5XFiXaDAF:-LmBZEl-EFJ5XFiXaDAG:bsee7ql) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/cdb7976c4c5f75de1f61b39a6f3e71b26fa7b969/docker/ffmpeg/Dockerfile#L166)):*
> ```Dockerfile
>     ln -s /apps/install/bin/ffprobe /usr/bin/ffprobe
> 
> ENTRYPOINT [ "/bin/bash" ]
> ```

Note to self: Run this.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32)* status: all files reviewed, 3 unresolved discussions (waiting on @bquinn17)

___
*[docker/ffmpeg/Dockerfile, line 30 at r2](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32#-LmB_wdk7l8WLznoAzDK:-LmB_wdl4cTDoXEQp0eC:b-s4oih9) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/cdb7976c4c5f75de1f61b39a6f3e71b26fa7b969/docker/ffmpeg/Dockerfile#L30)):*
> ```Dockerfile
> #############################################################################
> 
> FROM centos:7.4.1708
> ```

Change to `FROM centos:7`

I've tested with this change.
___
*[docker/ffmpeg/Dockerfile, line 33 at r2](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32#-LmB_zFQDnlvjTyeHtt0:-LmB_zFQDnlvjTyeHtt1:b-itxtgx) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/cdb7976c4c5f75de1f61b39a6f3e71b26fa7b969/docker/ffmpeg/Dockerfile#L33)):*
> ```Dockerfile
> 
> # Set up yum repo:
> RUN yum install -y epel-release deltarpm && yum update -y && \
> ```

Remove `yum update -y &&`

I've tested with this change.

**Review by bquinn17 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32)* status: all files reviewed, 3 unresolved discussions (waiting on @bquinn17 and @jrobble)

___
*[docker/ffmpeg/Dockerfile, line 30 at r2](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32#-LmB_wdk7l8WLznoAzDK:-LmFWD5S8BGZNCY9gGjd:b-896fix) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/cdb7976c4c5f75de1f61b39a6f3e71b26fa7b969/docker/ffmpeg/Dockerfile#L30)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change to `FROM centos:7`

I've tested with this change.
</blockquote></details>

Done.
___
*[docker/ffmpeg/Dockerfile, line 33 at r2](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32#-LmB_zFQDnlvjTyeHtt0:-LmFWB4464TB-Jn0YPjj:b-896fix) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/cdb7976c4c5f75de1f61b39a6f3e71b26fa7b969/docker/ffmpeg/Dockerfile#L33)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Remove `yum update -y &&`

I've tested with this change.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/32)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
