### PR TITLE
Upgrade to Python 3

### PR DESCRIPTION
**Pull request by brosenberg42**
Issue: https://github.com/openmpf/openmpf/issues/832
Associated PRs:
- https://github.com/openmpf/openmpf-build-tools/pull/36
- https://github.com/openmpf/openmpf-python-component-sdk/pull/22
- https://github.com/openmpf/openmpf-components/pull/138
- https://github.com/openmpf/openmpf/pull/1069
- https://github.com/openmpf/openmpf-docker/pull/70

This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/36)

### CODE REVIEW

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/36)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jrobble — COMMENTED** [review]
`README.md` has the following:

```
* To build the C++ Component SDK, the Java Component SDK, and all components you can run:

python build_components.py \
```

```
* Example: `python build_components.py -csdk ~/openmpf-projects/openmpf-cpp-component-sdk -jsdk ~/openmpf-projects/openmpf-java-component-sdk`
```

Please update both to `python3`.

--- 

Also, update the hashbang in:
- `openmpf-build-tools/mpf-component-dependency-finder/component_dependency_finder.py`
- `openmpf-build-tools/mpf-component-dependency-finder/test_component_dependency_finder.py`

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/36#-:-M7imSvj1JsW07vJ3syM:bm3xxze)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @brosenberg42 and @jrobble)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/36)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[mpf-component-dependency-finder/component_dependency_finder.py, line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf-build-tools/36#-M7ozU889n1HIc48S8Dr:-M7ozU8941KY8lcbd_6Z:b-xd5gv0) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/5c1d02877174aafb0b0ecb35c434a1fea11280af/mpf-component-dependency-finder/component_dependency_finder.py#L1)):*
> ```Python
> #! /usr/bin/env python
> ```

Please update to `python3`.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/36)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[mpf-component-dependency-finder/component_dependency_finder.py, line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf-build-tools/36#-M7ozU889n1HIc48S8Dr:-M7reebQCU5rEUjJ9qG6:b-896fix) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/5c1d02877174aafb0b0ecb35c434a1fea11280af/mpf-component-dependency-finder/component_dependency_finder.py#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update to `python3`.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/36)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
