### PR TITLE
Added UpdateVersion.py.

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-build-tools/3)

### CODE REVIEW

**Comment by brosenberg42** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[helper-scripts/UpdateVersion.py, line 45 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3#-KqOKx9o5W9Cpxe59xr9:-KqOKx9o5W9Cpxe59xrA:b-mhf3iv) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/85be691a1f1373882bd246c4770150df0dc7b8c2/helper-scripts/UpdateVersion.py#L45)):*
> ```Python
> 
>     if (len(sys.argv) != 3):
>         print "Usage: " + os.path.basename(__file__) + " <old_version_str> <new_version_str>"
> ```

os.path.basename should be `sys.argv[0]`

---

*[helper-scripts/UpdateVersion.py, line 74 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3#-KqOLQMHsLzdOMSmb5B_:-KqOLQMHsLzdOMSmb5Ba:bg1icro) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/85be691a1f1373882bd246c4770150df0dc7b8c2/helper-scripts/UpdateVersion.py#L74)):*
> ```Python
>     if (os.system(search_command) != 0):
>         print "Could not find search string in " + file_path + ":"
>         os.system("echo \"" + search_str + "\"")
> ```

Why not just call print here?

---

*[helper-scripts/UpdateVersion.py, line 83 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3#-KqOLzc4iI1UilgkDrzv:-KqOLzc4iI1UilgkDrzw:bg1icro) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/85be691a1f1373882bd246c4770150df0dc7b8c2/helper-scripts/UpdateVersion.py#L83)):*
> ```Python
>     if (exit_code != 0):
>         print "Could not replace search string in " + file_path + ":"
>         os.system("echo \"" + search_str + "\"")
> ```

Why not just call print here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[helper-scripts/UpdateVersion.py, line 45 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3#-KqOKx9o5W9Cpxe59xr9:-KqOgPpMksLwijwR1lcT:b-jnoxtt) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/85be691a1f1373882bd246c4770150df0dc7b8c2/helper-scripts/UpdateVersion.py#L45)):*
`sys.argv[0]` prints the full path name:

> [mpf@localhost openmpf-build-tools]$ ./helper-scripts/UpdateVersion.py 
> Usage: ./helper-scripts/UpdateVersion.py <old_version_str> <new_version_str>

`os.path.basename(__file__)` prints just the script name: "UpdateVersion.py"

> [mpf@localhost openmpf-build-tools]$ ./helper-scripts/UpdateVersion.py 
> Usage: UpdateVersion.py <old_version_str> <new_version_str>

I preferred the latter. Is the former more standard? Do you have a preference?

---

*[helper-scripts/UpdateVersion.py, line 74 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3#-KqOLQMHsLzdOMSmb5B_:-KqOg4fxm9rYCvszP83n:bm30ei) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/85be691a1f1373882bd246c4770150df0dc7b8c2/helper-scripts/UpdateVersion.py#L74)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Why not just call print here?
</blockquote></details>

This string has escape characters that `print` will show as escape characters but `echo` won't:

`"echo \\\"                           Installing OpenMPF "`

The reason for the escape characters is to by able to pass the correct string to `os.system()`.

---

*[helper-scripts/UpdateVersion.py, line 83 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3#-KqOLzc4iI1UilgkDrzv:-KqOgNe4Xt5Bl9PzulC2:b-q64pkt) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/85be691a1f1373882bd246c4770150df0dc7b8c2/helper-scripts/UpdateVersion.py#L83)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Why not just call print here?
</blockquote></details>

See above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[helper-scripts/UpdateVersion.py, line 45 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3#-KqOKx9o5W9Cpxe59xr9:-KqOleIa9O7mgk7Xnypj:bkygzq) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/85be691a1f1373882bd246c4770150df0dc7b8c2/helper-scripts/UpdateVersion.py#L45)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`sys.argv[0]` prints the full path name:

> [mpf@localhost openmpf-build-tools]$ ./helper-scripts/UpdateVersion.py 
> Usage: ./helper-scripts/UpdateVersion.py <old_version_str> <new_version_str>

`os.path.basename(__file__)` prints just the script name: "UpdateVersion.py"

> [mpf@localhost openmpf-build-tools]$ ./helper-scripts/UpdateVersion.py 
> Usage: UpdateVersion.py <old_version_str> <new_version_str>

I preferred the latter. Is the former more standard? Do you have a preference?
</blockquote></details>

Most Linux programs print the full path. For example:
```
[~] -> grep
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.


[~] -> /usr/bin/grep
Usage: /usr/bin/grep [OPTION]... PATTERN [FILE]...
Try '/usr/bin/grep --help' for more information.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3)*

**Comment by jrobble** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[helper-scripts/UpdateVersion.py, line 45 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3#-KqOKx9o5W9Cpxe59xr9:-KqOt1KGvYSKerqW1cso:b-iqxjsm) ([raw file](https://github.com/openmpf/openmpf-build-tools/blob/85be691a1f1373882bd246c4770150df0dc7b8c2/helper-scripts/UpdateVersion.py#L45)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Most Linux programs print the full path. For example:
```
[~] -> grep
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.


[~] -> /usr/bin/grep
Usage: /usr/bin/grep [OPTION]... PATTERN [FILE]...
Try '/usr/bin/grep --help' for more information.
```
</blockquote></details>

Good call. I updated the script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-build-tools/3#-:-KqP3oPOtKKwsCj-Syiu:bnfp4nl)*

**Pull request merged**
